
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
spec:
  serviceName: pg-svc
  selector:
    matchLabels:
      app: pg
  replicas: 1
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres:latest
          volumeMounts:
            - name: pg-pvc
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata

  volumeClaimTemplates:
    - metadata:
        name: pg-pvc
      spec:
        storageClassName: "nfs"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: pg-svc
spec:
  selector:
    app: pg
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432

