
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
spec:
  serviceName: pg-svc
  selector:
    matchLabels:
      app: pgsql
  replicas: 1
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql-db
          image: postgres:latest
          volumeMounts:
            - name: pg-pvc
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata

  volumeClaimTemplates:
    - metadata:
        name: pg-pvc
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: pg-svc
spec:
  selector:
    app: pgsql
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.20
    path: /home/nfs
