apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-and-back-deployment
  labels:
    app: front-and-back
spec:
  selector:
    matchLabels:
      app: front-and-back
  template:
    metadata:
      labels:
        app: front-and-back
    spec:
      containers:
      - name: front
        image: rowhe/netology:dz131_front_app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: back
        image: rowhe/netology:dz131_back_app
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
---

apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: front-and-back

---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30002
  selector:
    app: front-and-back
