version: "3.7"

services:
  frontend:
    image: rowhe/netology:dz131_front_app
#    build: ./frontend
    ports:
      - 8000:80

  backend:
    image: rowhe/netology:dz131_back_app
#    build: ./backend
    links:
      - db
    ports:
      - 9000:9000

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news
