apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-and-back-deployment
  labels:
    app: front-and-back
spec:
  selector:
    matchLabels:
      app: front-and-back
  template:
    metadata:
      labels:
        app: front-and-back
    spec:
      containers:
      - name: front
        image: rowhe/netology:dz131_front_app
        ports:
        - containerPort: 80
      - name: back
        image: rowhe/netology:dz131_back_app
        command: ["sleep", "3600"]