apiVersion: v1
kind: Service
metadata:
  name: front-and-back-service
    labels:
      app: front-and-back
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 8080
  selector:
    app: front-and-back