apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: back
        image: rowhe/netology:dz131_back_app
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30002
  selector:
    app: backend
