apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: rowhe/netology:dz131_front_app
        imagePullPolicy: Always
        ports:

---

apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: front


