apiVersion: v1
kind: Pod
metadata:
  name: pod1-nfs
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/static"
          name: nfs1-volume
  volumes:
    - name: nfs1-volume
      persistentVolumeClaim:
        claimName: pvc