apiVersion: v1
kind: Pod
metadata:
  name: pod2-nfs
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/static"
          name: nfs2-volume
  volumes:
    - name: nfs2-volume
      persistentVolumeClaim:
        claimName: pvc